apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: neuvectorusages.neuvector.com
spec:
  group: neuvector.com
  names:
    kind: NeuvectorUsage
    listKind: NeuvectorUsageList
    plural: neuvectorusages
    singular: neuvectorusage
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          value:
            type: integer
          version:
            type: string
        type: object
    served: true
    storage: true
