apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: neuvectorusagerecords.neuvector.com
spec:
  group: neuvector.com
  names:
    kind: NeuvectorUsageRecord
    listKind: NeuvectorUsageRecordList
    plural: neuvectorusagerecords
    singular: neuvectorusagerecord
    shortNames:
      - nur
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          usage:
            type: integer
          extensions:
            type: string
          version:
            type: string
          timestamp:
            type: string
        required:
          - usage
          - version
          - timestamp
        type: object
    served: true
    storage: true
