apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: settings.neuvector.com
spec:
  group: neuvector.com
  names:
    kind: Setting
    listKind: SettingList
    plural: settings
    singular: setting
  scope: Cluster
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: neuvectorusernotifications.neuvector.com
spec:
  group: neuvector.com
  names:
    kind: NeuvectorUserNotification
    listKind: NeuvectorUserNotificationList
    plural: neuvectorusernotifications
    singular: neuvectorusernotification
  scope: Cluster
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
