apiVersion: v1
kind: ServiceAccount
metadata:
  name: csp
  namespace: neuvector
#  annotations:
#    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountNumber }}:role/{{ .Values.aws.roleName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-csp-adapter-cluster-role
rules:
- apiGroups:
  - neuvector.com
  resources:
  - neuvectorusagerecords
  resourceNames:
  - neuvector-usage
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-csp-adapter-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: neuvector-csp-adapter-cluster-role
subjects:
  - kind: ServiceAccount
    name: csp
    namespace: neuvector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: neuvector-csp-adapter-role
  namespace: neuvector
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - csp-adapter-cache
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - csp-config
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: neuvector-csp-adapter-binding
  namespace: neuvector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: neuvector-csp-adapter-role
subjects:
  - kind: ServiceAccount
    name: csp
    namespace: neuvector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuvector-csp-pod
  namespace: neuvector
spec:
  selector:
    matchLabels:
      app: neuvector-csp-pod
  template:
    metadata:
      labels:
        app: neuvector-csp-pod
    spec:
      containers:
      - env:
        - name: ADAPTER_NAMESPACE
          value: 'neuvector'
        - name: USAGE_CRD_PLURAL
          value: "neuvectorusagerecords"
        - name: USAGE_RESOURCE
          value: "neuvector-usage"
        - name: USAGE_API_VERSION
          value: "v1"
        - name: USAGE_API_GROUP
          value: "neuvector.com"
        image: registry.opensuse.org/home/seanmarlow/containers/containers/csp-billing-adapter-container-local:latest
        name: neuvector-csp-pod
        imagePullPolicy: "Always"
      serviceAccount: csp
      serviceAccountName: csp
