apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nvwafsecurityrules.neuvector.com
spec:
  group: neuvector.com
  names:
    kind: NvWafSecurityRule
    listKind: NvWafSecurityRuleList
    plural: nvwafsecurityrules
    singular: nvwafsecurityrule
  scope: Cluster
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
