apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nvadmissioncontrolsecurityrules.neuvector.com
spec:
  group: neuvector.com
  names:
    kind: NvAdmissionControlSecurityRule
    listKind: NvAdmissionControlSecurityRuleList
    plural: nvadmissioncontrolsecurityrules
    singular: nvadmissioncontrolsecurityrule
  scope: Cluster
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
