apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nvdlpsecurityrules.neuvector.com
spec:
  group: neuvector.com
  names:
    kind: NvDlpSecurityRule
    listKind: NvDlpSecurityRuleList
    plural: nvdlpsecurityrules
    singular: nvdlpsecurityrule
  scope: Cluster
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
