name: Build scanner image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git clone https://github.com/neuvector/manager.git
          cd ./vul-dbgen
          git clone --depth 1 https:/github.com/neuvector/vul-source.git
          VULN_VER=x.xxx make db
          cd ..

          git clone https://github.com/neuvector/scanner.git
          mkdir -p scanner/data
          cp ./vul-dbgen/cvedb.regular scanner/data

          cd ./scanner
          make binary
          cd ..

          cp scanner/Makefile Makefile
          cp scanner/build/dockerignore .dockerignore
          make scanner_image
